#!/bin/bash
set -e

DOCKER_DOCKERFILE_NAME="${POSTGRES_VERSION}${VARIANT:+-${VARIANT}}"
DOCKER_IMAGE_VERSION="${DOCKER_DOCKERFILE_NAME}${NODE_VERSION:+-node${NODE_VERSION}}"
DOCKER_IMAGE_TAG="${DOCKER_HUB_REPOSITORY}:${DOCKER_IMAGE_VERSION}"
DOCKER_IMAGE_ARTIFACT_PATH="./build/${DOCKER_IMAGE_VERSION}.tar"
DOCKER_CONTAINER_NAME="postgres-node_${DOCKER_IMAGE_VERSION}"

# https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
echo "DOCKER_DOCKERFILE_NAME=${DOCKER_DOCKERFILE_NAME}" >> $GITHUB_ENV
echo "DOCKER_IMAGE_VERSION=${DOCKER_IMAGE_VERSION}" >> $GITHUB_ENV
echo "DOCKER_IMAGE_TAG=${DOCKER_IMAGE_TAG}" >> $GITHUB_ENV
echo "DOCKER_IMAGE_ARTIFACT_PATH=${DOCKER_IMAGE_ARTIFACT_PATH}" >> $GITHUB_ENV
echo "DOCKER_CONTAINER_NAME=${DOCKER_CONTAINER_NAME}" >> $GITHUB_ENV
