#!/bin/bash
set -e

export DOCKER_DOCKERFILE_NAME="${POSTGRES_VERSION}${VARIANT:+-${VARIANT}}"
export DOCKER_IMAGE_VERSION="${DOCKER_DOCKERFILE_NAME}${NODE_VERSION:+-node${NODE_VERSION}}"
export DOCKER_IMAGE_TAG="${DOKER_HUB_REPOSITORY}:${IMAGE_VERSION}"
export DOCKER_IMAGE_ARTIFACT_PATH="./build/${IMAGE_VERSION}.tar"
